### ISSUE TITLE
Not Working with geoJSON polygon

### ISSUE THREAD

**Issue by sag3ll0** [ProminentEdge/leaflet-measure-path#15]
var geo = JSON.parse('{"type": "FeatureCollection","features": [{"type": "Feature","properties": {},"options": {"showMeasurements": true},"geometry": {"type": "Polygon","coordinates": [[[37.77099609375,55.819801652442436],[36.650390625,55.41030721005218],[39.08935546875,55.435246897869995],[39.210205078125,55.91227293006361],[38.770751953125,56.28605924471002],[37.77099609375,55.819801652442436]]]}}]}');
        var geoL = L.geoJSON(geo, {
            showMeasurements: true
        }).addTo(map).showMeasurements();

raise Uncaught TypeError: L.geoJSON(...).addTo(...).showMeasurements is not a function.
Can you add this functions?

**Comment by perliedman** [comment]
Hi there,
the problem here is that leaflet-measurement-path works on _paths_, but `L.GeoJSON` does not inherit from `L.Path`, so it will not have the `showMeasurements` method, and not understand the `showMeasurements` option.

You can enable measurments for all layers within a GeoJSON layer by using `onEachFeature`:

```js
var geoL = L.geoJSON(geo, {
    onEachFeature: function(feature, layer) {
        // Points are normally created as markers, which are not
        // paths, so first check if the layer has a showMeasurements method
        if (layer.showMeasurements) {
            layer.showMeasurements();
        }
    }
}).addTo(map);
```

**Comment by sag3ll0** [comment]
![image](https://cloud.githubusercontent.com/assets/18505406/24378070/52075fce-134a-11e7-8c6a-78a41d1fe77c.png)
i trying, but its not working. What i do wrong?

**Comment by perliedman** [comment]
Hm, not sure, and it's very hard to tell from just looking at a screenshot. Any errors in the console or so? What happens when you step through the code, do the layers have the `showMeasurements` method?

**Comment by sag3ll0** [comment]
its working with 
`        var geo2 = JSON.parse(
            '{"type": "FeatureCollection","features": [{"type": "Feature","properties": {},"options": {"showMeasurements": true},"geometry": {"type": "Polygon","coordinates": [[[37.77099609375,55.819801652442436],[36.650390625,55.41030721005218],[39.08935546875,55.435246897869995],[39.210205078125,55.91227293006361],[38.770751953125,56.28605924471002],[37.77099609375,55.819801652442436]]]}}]}'
        );
        var geoL2 = L.geoJSON(geo2, {
            showMeasurements: true
        }).addTo(map);`

`.showMeasurements()` not needed
