### ISSUE TITLE
Leaflet 1+

### ISSUE THREAD

**Issue by flightsurvey** [ProminentEdge/leaflet-measure-path#16]
Are you sure that this works with Leaflet 1+? I have the library correctly referenced and have implemented so:
`
    newArea = L.polygon([e.layer.getLatLngs(0)],{
      color: '#6d8bc7',
      contextmenu: true,
      contextmenuInheritItems: true,
      alt: 'area'    
    }).addTo(newAssignmentDetails).showMeasurements();
    newAssignmentDetails.addTo(map);
`
And get an error saying "showMeasurement is not a function".

**Comment by flightsurvey** [comment]
Update:

This works:

`        L.geoJson(definedAreaCoordinates,{
          contextmenu: true,
          contextmenuInheritItems: true,
          showMeasurements: true,
          onEachFeature: function (feature, layer) {
            layer._leaflet_id = -1;
            layer.bindTooltip('Assignment',{direction: 'top', sticky: true});
            layer.setStyle({weight: 2});
            definedAreaPolygon = layer;
            tempLayer = layer;
            definedArea.addLayer(layer);
          },         
        }).addTo(assignmentArea);
`

But this doesn't

`    newArea = L.polygon([e.layer.getLatLngs(0)],{
      showMeasurements: true,
      color: '#6d8bc7',
      contextmenu: true,
      contextmenuInheritItems: true,
      alt: 'area'
    }).addTo(newAssignmentDetails);
`

**Comment by perliedman** [comment]
Hi,
sounds weird. If you check the example, it definitely uses Leaflet 1.0, and it does more or less exactly what you write above: https://github.com/ProminentEdge/leaflet-measure-path/blob/master/example/index.html#L56

You can also see a running version of the demo here, running with latest Leaflet: http://playground-leaflet.rhcloud.com/xut/edit?html,output

So I'd guess something related to your setup causes this issue. Any errors in the log, etc.? Could you provide an example illustrating the problem?

**Comment by flightsurvey** [comment]
Hi and thanks for getting back. I cut my losses and modified the code so that all polygons requiring text are created from geoJSON and all is fine. I'm afraid that I don't really have time to provide an example but thank you for your help anyway.

**Comment by perliedman** [comment]
Ok, closing for now. Feel free to add more information if you believe this is still an issue with leaflet-measure-path.
