### ISSUE TITLE
Area in Hectares

### ISSUE THREAD

**Issue by Metalyph** [ProminentEdge/leaflet-measure-path#20]
Is there some place one can view all the documentation for leaflet-measure-path? Specifically for all the showMeasurements() options?

I noticed in the example there's an easy way to switch the units to imperial, which I didn't see in the documentation.  Is there some way to set an area measurement to to always use hectares as the unit of measurement?

**Comment by perliedman** [comment]
Hi!
Sorry, there's no more docs than what is available in the README.

You can provide your own function for formatting the area label by using the `formatArea` option that is in the docs.

**Comment by flywire** [comment]
Can you provide a `formatArea` function example for Ha to 1 decimal place?
