### ISSUE TITLE
L.GeoJSON support 

### ISSUE THREAD

**Issue by hellracer** [ProminentEdge/leaflet-measure-path#24]
Hi guys,

Any chances this could also be implemented on L.GeoJSON? thanks!

**Comment by perliedman** [comment]
Hi! You should already be able to use this with a GeoJSON using the `onEachFeature` option to enable measurements:

```js
var geoJsonLayer = L.geoJson(geoJson, {
    onEachFeature: function(feature, layer) {
        if (layer.showMeasurements) {
            layer.showMeasurements();
        }
    }
});
```

Haven't actually tried it, but should work. Give a shout if you encounter any trouble!

**Comment by 2803media** [comment]
hi @perliedman I try your code for a L.geoJson but it display nothing (or I miss something).
I made an example of the code just here
https://lecadastre.com/wp-content/themes/codium-dn/test-mesure.html

Thanks for your input and your code too ;)
