### ISSUE TITLE
Converting to work with Mapbox GL

### ISSUE THREAD

**Issue by JAugustusSmith** [ProminentEdge/leaflet-measure-path#25]
I'm updating my maps from Leaflet to MapboxGL, and wanted to keep this functionality.

I want to create a version of leaflet-measure-path (mapboxgl-measure-path) based on this code.
Do I need to get permission?
Has somebody already done this work?

**Comment by perliedman** [comment]
Hi! Interesting, I am not aware of any such work being done, but I do not use Mapbox GL actively, so I am not up to date on what happens in their ecosystem.

You do not need any permission, feel free to base your work on leaflet-measure-path, as long as you keep [the license](https://github.com/ProminentEdge/leaflet-measure-path/blob/master/LICENSE.md)!
