### ISSUE TITLE
When removed polyline I get error

### ISSUE THREAD

**Issue by SweetViper** [ProminentEdge/leaflet-measure-path#26]
Hey. In my code, on mouseout  hideMeasurements () is executed. But when I delete an object, an error occurs. Could you add a check to the beginning of the method `if (!this._map || this._measurementLayer) return this;` Thank you.

**Comment by WilliamRADFunk** [comment]
If this gets merged:

https://github.com/ProminentEdge/leaflet-measure-path/pull/27

You'll have the...

if (!this._map) return this;

...part at least.

**Comment by perliedman** [comment]
#27 has been merged and released as 1.4.0, so I'm closing this. I'll happily re-open if the issue still exists, just tell me.
