### ISSUE TITLE
Does not work with Leaflet 1.0.1 and Leaflet.Editable 1.0.0-rc.2

### ISSUE THREAD

**Issue by hrishiballal** [ProminentEdge/leaflet-measure-path#7]
The demo works fine with Leaflet 0.7+ but when I try using the latest leaflet and leaflet editable, the polyline display works but the polygon area calculations do not.

**Comment by perliedman** [comment]
Hi there, there was some issues with this plugin and Leaflet 1.0, but I've fixed them and released version 1.3.0, so please update and try again!
