### ISSUE TITLE
showOnHover doesn't work

### ISSUE THREAD

**Issue by bhaskarvk** [ProminentEdge/leaflet-measure-path#9]
Setting showOnHover to true doesn't seem to have any effect. In fact it doesn't seem to be getting used anywhere in the code after being set.

**Comment by perliedman** [comment]
Huh, yeah it seems I started to add that but never finished. Sorry about that.

This should be fairly easy to add, and help is much appreciated, this will unfortunately not end up at the top of my todo as it is now.

**Comment by WilliamRADFunk** [comment]
@perliedman I might be interested in implementing this. If so, do you have any forking/pull requesting/ quality conditions I should read before beginning?

**Comment by perliedman** [comment]
@WilliamRADFunk nothing in particular, try to stick to the existing code style (looks like 4 spaces, not tabs as indentation), try not to go over board with changes 😄 

Very thankful if you can spend some time on this!

**Comment by WilliamRADFunk** [comment]
@perliedman : I implemented showOnHover as your documentation described it.

I added examples in the example page, and unit tests to cover my additions. Let me know if it fails to meet any style criteria, or if there are any problems you notice (though the change was pretty localized).

Examples and unit tests added for good measure.

**Comment by perliedman** [comment]
Finally fixed by @WilliamRADFunk in #27 :tada:

**Comment by flywire** [comment]
@perliedman - _not_ WYSIWIG. Please update [Leaflet Measure Path demo] http://prominentedge.com/leaflet-measure-path/ to run https://github.com/ProminentEdge/leaflet-measure-path/blob/master/example/index.html
